### ISSUE TITLE
The spacebar key may crash the game when outside of a world

### ISSUE THREAD

**Issue by Kevadroz** [FriederHannenheim/Boost-Boots#3]
[latest.log](https://github.com/FriederHannenheim/Boost-Boots/files/5439959/latest.log)

Happened on the world creation screen, while tipping the world title.
I know it doesn't happen to everyone, i know people with the exact same configuration (modpack) and they cant replicate the issue.

OS: Manjaro (Linux x64)

**Comment by FriederHannenheim** [comment]
Are you on 1.15 or 1.16?

**Comment by Kevadroz** [comment]
1.16

**Comment by FriederHannenheim** [comment]
Fixed in https://github.com/FriederHannenheim/Boost-Boots/commit/fbba422b513c1332a37383d9768687ff4c059d39
